
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Faizan Habib
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageRoomBtn = new javax.swing.JButton();
        newStudentBtn = new javax.swing.JButton();
        updateDeleteBtn = new javax.swing.JButton();
        studentFeesBtn = new javax.swing.JButton();
        livingBtn = new javax.swing.JButton();
        leavedBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageRoomBtn.setBackground(new java.awt.Color(204, 204, 204));
        manageRoomBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageRoomBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room.png"))); // NOI18N
        manageRoomBtn.setText("Manage Room");
        manageRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRoomBtnActionPerformed(evt);
            }
        });
        getContentPane().add(manageRoomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 245, -1));

        newStudentBtn.setBackground(new java.awt.Color(204, 204, 204));
        newStudentBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new student.png"))); // NOI18N
        newStudentBtn.setText("New Student");
        newStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 245, -1));

        updateDeleteBtn.setBackground(new java.awt.Color(204, 204, 204));
        updateDeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update & Delete Student.png"))); // NOI18N
        updateDeleteBtn.setText("Update & Delete");
        updateDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 245, -1));

        studentFeesBtn.setBackground(new java.awt.Color(204, 204, 204));
        studentFeesBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentFeesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fees.png"))); // NOI18N
        studentFeesBtn.setText("Student Fees");
        getContentPane().add(studentFeesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 245, -1));

        livingBtn.setBackground(new java.awt.Color(204, 204, 204));
        livingBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        livingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all student living.png"))); // NOI18N
        livingBtn.setText("Living Students");
        livingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(livingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 245, -1));

        leavedBtn.setBackground(new java.awt.Color(204, 204, 204));
        leavedBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        leavedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Leaved students.png"))); // NOI18N
        leavedBtn.setText("Leaved Student");
        leavedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavedBtnActionPerformed(evt);
            }
        });
        getContentPane().add(leavedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 245, -1));

        logoutBtn.setBackground(new java.awt.Color(204, 204, 204));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

        exitBtn.setBackground(new java.awt.Color(204, 204, 204));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home background.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRoomBtnActionPerformed
        // TODO add your handling code here:
        manageRoomBtn.setForeground(Color.red);
        manageRoomBtn.setBackground(new Color(255, 255, 255));
        new manageRoom().setVisible(true);
    }//GEN-LAST:event_manageRoomBtnActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        manageRoomBtn.setForeground(new JButton().getForeground());
        manageRoomBtn.setBackground(new JButton().getBackground());
        
        newStudentBtn.setForeground(new JButton().getForeground());
        newStudentBtn.setBackground(new JButton().getBackground());
        
        updateDeleteBtn.setForeground(new JButton().getForeground());
        updateDeleteBtn.setBackground(new JButton().getBackground());
        
        studentFeesBtn.setForeground(new JButton().getForeground());
        studentFeesBtn.setBackground(new JButton().getBackground());
        
        livingBtn.setForeground(new JButton().getForeground());
        livingBtn.setBackground(new JButton().getBackground());
        
        leavedBtn.setForeground(new JButton().getForeground());
        leavedBtn.setBackground(new JButton().getBackground());
    }//GEN-LAST:event_formWindowGainedFocus

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void newStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentBtnActionPerformed
        // TODO add your handling code here:
        newStudentBtn.setForeground(Color.red);
        newStudentBtn.setBackground(new Color(255, 255, 255));
        new newStudent().setVisible(true);
    }//GEN-LAST:event_newStudentBtnActionPerformed

    private void updateDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteBtnActionPerformed
        // TODO add your handling code here:
        updateDeleteBtn.setForeground(Color.red);
        updateDeleteBtn.setBackground(new Color(255, 255, 255));
        new updateDelete().setVisible(true);
    }//GEN-LAST:event_updateDeleteBtnActionPerformed

    private void livingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livingBtnActionPerformed
        // TODO add your handling code here:
        livingBtn.setForeground(Color.red);
        livingBtn.setBackground(new Color(255, 255, 255));
        new livingStudents().setVisible(true);
    }//GEN-LAST:event_livingBtnActionPerformed

    private void leavedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavedBtnActionPerformed
        // TODO add your handling code here:
        leavedBtn.setForeground(Color.red);
        leavedBtn.setBackground(new Color(255, 255, 255));
        new leavedStudents().setVisible(true);
    }//GEN-LAST:event_leavedBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton leavedBtn;
    private javax.swing.JButton livingBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageRoomBtn;
    private javax.swing.JButton newStudentBtn;
    private javax.swing.JButton studentFeesBtn;
    private javax.swing.JButton updateDeleteBtn;
    // End of variables declaration//GEN-END:variables
}
