import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Faizan Habib
 */
public class newStudent extends javax.swing.JFrame {
    public void clear() {
        studentField.setText("");
        fatherField.setText("");
        enrolField.setText("");
        courseField.setText("");
        batchField.setText("");
        facultyField.setText("");
        deptField.setText("");
        mobileField.setText("");
        addressField.setText("");
        roomComboBox.removeAllItems();
        roomNumber();
    }
    
    public void roomNumber() {
        int i = 0;
        
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from room where activate = 'Yes' and roomStatus = 'Not Booked'");
            
            while (rs.next()) {
                i = 1;
                roomComboBox.addItem(rs.getString(1));
            }
            
            if (i == 0) { // If no room available
                saveBtn.setVisible(false); // Disable Save Button
                JOptionPane.showMessageDialog(null, "All rooms are already booked.");
                setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    /**
     * Creates new form newStudent
     */
    public newStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        studentName = new javax.swing.JLabel();
        fatherName = new javax.swing.JLabel();
        enrolNumber = new javax.swing.JLabel();
        batch = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        faculty = new javax.swing.JLabel();
        dept = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        studentField = new javax.swing.JTextField();
        fatherField = new javax.swing.JTextField();
        enrolField = new javax.swing.JTextField();
        courseField = new javax.swing.JTextField();
        batchField = new javax.swing.JTextField();
        facultyField = new javax.swing.JTextField();
        deptField = new javax.swing.JTextField();
        mobileField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        roomComboBox = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 150));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close all jframe.png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, -1));

        studentName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentName.setText("Student Name");
        getContentPane().add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 49, -1, -1));

        fatherName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fatherName.setText("Father Name");
        getContentPane().add(fatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 93, -1, -1));

        enrolNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enrolNumber.setText("Enrolment Number");
        getContentPane().add(enrolNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 137, -1, -1));

        batch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        batch.setText("Batch");
        getContentPane().add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 225, -1, -1));

        mobile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobile.setText("Mobile Number");
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 357, -1, -1));

        course.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        course.setText("Course");
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 181, -1, -1));

        faculty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        faculty.setText("Faculty");
        getContentPane().add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 269, -1, -1));

        dept.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dept.setText("Department");
        getContentPane().add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 313, -1, -1));

        address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        address.setText("Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 401, -1, -1));

        room.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        room.setText("Room Number");
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 465, -1, -1));

        studentField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(studentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 46, 350, -1));

        fatherField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(fatherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 90, 350, -1));

        enrolField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(enrolField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 134, 350, -1));

        courseField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(courseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 178, 350, -1));

        batchField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(batchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 222, 350, -1));

        facultyField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(facultyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 266, 350, -1));

        deptField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(deptField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 310, 350, -1));

        mobileField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(mobileField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 354, 350, -1));

        addressField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 398, 350, -1));

        roomComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(roomComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 462, 90, -1));

        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pages background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        roomNumber();
    }//GEN-LAST:event_formComponentShown

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String studentName = studentField.getText();
        String fatherName = fatherField.getText();
        String enrolNum = enrolField.getText();
        String course = courseField.getText();
        String batch = batchField.getText();
        String faculty = facultyField.getText();
        String dept = deptField.getText();
        String mobileNum = mobileField.getText();
        String address = addressField.getText();
        String roomNum = (String)roomComboBox.getSelectedItem();
        String status = "living";
        
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into student value(?, ?, ? ,? ,?, ?, ?, ? ,? ,?, ?)");
            ps.setString(1, studentName);
            ps.setString(2, fatherName);
            ps.setString(3, enrolNum);
            ps.setString(4, course);
            ps.setString(5, batch);
            ps.setString(6, faculty);
            ps.setString(7, dept);
            ps.setString(8, mobileNum);
            ps.setString(9, address);
            ps.setString(10, roomNum);
            ps.setString(11, status);
            ps.executeUpdate();
            
            PreparedStatement ps1 = con.prepareStatement("update room set roomStatus = 'Booked' where roomNumber = ?");
            ps1.setString(1, roomNum);
            ps1.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel batch;
    private javax.swing.JTextField batchField;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel course;
    private javax.swing.JTextField courseField;
    private javax.swing.JLabel dept;
    private javax.swing.JTextField deptField;
    private javax.swing.JTextField enrolField;
    private javax.swing.JLabel enrolNumber;
    private javax.swing.JLabel faculty;
    private javax.swing.JTextField facultyField;
    private javax.swing.JTextField fatherField;
    private javax.swing.JLabel fatherName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel mobile;
    private javax.swing.JTextField mobileField;
    private javax.swing.JLabel room;
    private javax.swing.JComboBox<String> roomComboBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField studentField;
    private javax.swing.JLabel studentName;
    // End of variables declaration//GEN-END:variables
}
